### ISSUE TITLE
安装成功后：休眠不能唤醒，耳机不工作，亮度调节无

### ISSUE THREAD

**Issue by Xiwen-Lu** [yCatDev/asus_x542un-hackintosh#3]
如上面老哥所说，我使用“黑果小乒”的efi成功引导安装完系统，之后再替换github中的四叶草引导文件，成功。

现在的个人问题如下：
1. 休眠后不能唤醒
2. 插入耳机后无法播放声音，外放正常
3. 没有亮度调节功能

**Comment by yCatDev** [comment]
Hi, I really do not know why this option does not work, most likely the reason is in the patches that I did specifically for my laptop. Perhaps our modifications are too different. As for the sleep option, it is quite possible that it does not work at all, I will clarify this in the description.

**Comment by Xiwen-Lu** [comment]
> 嗨，我真的不知道为什么该选项不起作用，最可能的原因是我专门为笔记本电脑制作的补丁。也许我们的修改太不同了。至于睡眠选项，很可能根本不起作用，我将在说明中对此进行澄清。

Thank you very much ! Anyway
